### ISSUE TITLE
Migration of old phonebooks broken

### ISSUE THREAD

**Issue by urstruktur** [krachzack/fernspieleditor#14]
When loading old phonebooks speech text is not transferred.
Thank you for caring!

**Comment by krachzack** [comment]
@urstruktur I am pretty sure this is fixed now. I tried it with a file generated from an older version but I am not sure which version the files on your machine use.

Could you supply me with your collection of classic phonebooks so I can write proper automated tests for the migration?

**Comment by urstruktur** [comment]
It seems to work smoothly now.
As you requested I attach a collection of classic phonebooks. People like the classics.
[phonebooks.zip](https://github.com/krachzack/fernspieleditor/files/3720379/phonebooks.zip)
